# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: hsuallan/syosetu-com-spider
        ref: dev
        path: code
    - name: Use Node.js latest
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - name: ls
      run: ls -al
    - name: cd+ls2
      run: |
        cd ./code
        ls -al
    - name: cd+ls3
      run: |
        cd code/
        ls -al
    - name: Execute
      run: node code/index.js n2501fv 180
      
    - name: Update file on GitHub
      uses: alexesprit/action-update-file@v0.2.3
      with:
        # Commit message
        commit-msg: add file
        # Path to file to update
        file-path: code/novels/n2501fv/
        # GitHub token
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}
        branch: release
